(defun индивидуумы (x)
                   (if (null x) ()
                     (let ((m (member (first x) (rest x))))
                       (if (null m) (cons (first x) ( индивидуумы (rest x)))
                         ( индивидуумы (remove (first x) x))
                       )
                     )
                   )
                 )
